[versions]
kotlin = "2.3.0-Beta2"
gson = "2.13.2"

[libraries]
gson = {module = "com.google.code.gson:gson", version.ref = "gson"}

[plugins]
kotlin = {id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}